In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json

# Problem 2

In [31]:
# Read CSV
url = 'https://ies-python-midterm.s3.eu-central-1.amazonaws.com/companies/companies_no_subindustry.csv'
df = pd.read_csv(url)
df

,Symbol,Security,GICS Sector,hq,included,Founded
0,MMM,3M,Industrials,"Saint Paul, Minnesota",09.08.1976,1902
1,AOS,A. O. Smith,Industrials,"Milwaukee, Wisconsin",26.07.2017,1916
2,ABT,Abbott,Health Care,"North Chicago, Illinois",31.03.1964,1888
3,ABBV,AbbVie,Health Care,"North Chicago, Illinois",31.12.2012,2013 (1888)
4,ABMD,Abiomed,Health Care,"Danvers, Massachusetts",31.05.2018,1981
...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,"Louisville, Kentucky",06.10.1997,1997
499,ZBRA,Zebra Technologies,Information Technology,"Lincolnshire, Illinois",23.12.2019,1969
500,ZBH,Zimmer Biomet,Health Care,"Warsaw, Indiana",07.08.2001,1927
501,ZION,Zions Bancorporation,Financials,"Salt Lake City, Utah",22.06.2001,1873
502,ZTS,Zoetis,Health Care,"Parsippany, New Jersey",21.06.2013,1952

In [80]:
df['included'].isna().sum()

45

In [82]:
completedf = df[df['included'].notna()]
completedf

,Symbol,Security,GICS Sector,hq,included,Founded
0,MMM,3M,Industrials,"Saint Paul, Minnesota",09.08.1976,1902
1,AOS,A. O. Smith,Industrials,"Milwaukee, Wisconsin",26.07.2017,1916
2,ABT,Abbott,Health Care,"North Chicago, Illinois",31.03.1964,1888
3,ABBV,AbbVie,Health Care,"North Chicago, Illinois",31.12.2012,2013 (1888)
4,ABMD,Abiomed,Health Care,"Danvers, Massachusetts",31.05.2018,1981
...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,"Louisville, Kentucky",06.10.1997,1997
499,ZBRA,Zebra Technologies,Information Technology,"Lincolnshire, Illinois",23.12.2019,1969
500,ZBH,Zimmer Biomet,Health Care,"Warsaw, Indiana",07.08.2001,1927
501,ZION,Zions Bancorporation,Financials,"Salt Lake City, Utah",22.06.2001,1873
502,ZTS,Zoetis,Health Care,"Parsippany, New Jersey",21.06.2013,1952

In [88]:
pd.options.mode.chained_assignment = None
completedf['included'] = pd.to_datetime(completedf['included'], dayfirst=True,errors='coerce')

In [90]:
completedf['founded'].average()

KeyError: 'founded'

In [109]:
from datetime import date

def calculate_age(num):
    x = pd.to_datetime('today') - completedf['included']
   
    return x

calculate_age(completedf)

0     16898 days 19:35:27.552668
1      1937 days 19:35:27.552668
2     21412 days 19:35:27.552668
3      3605 days 19:35:27.552668
4      1628 days 19:35:27.552668
                 ...
498    9170 days 19:35:27.552668
499    1057 days 19:35:27.552668
500    7769 days 19:35:27.552668
501    7815 days 19:35:27.552668
502    3433 days 19:35:27.552668
Name: included, Length: 458, dtype: timedelta64[ns]

In [116]:
completedf.nunique()

Symbol         458
Security       458
GICS Sector     11
hq             243
included       350
Founded        186
dtype: int64

In [117]:
sector_counts = df["GICS Sector"].value_counts()
sector_counts

KeyError: 'GICS Sector'